name: Cron - dailyValorantMoments

on:
  schedule:
    # Runs “At 12:00.” UTC (see https://crontab.guru)
    - cron: "0 12 * * *"

jobs:
  cron-dailyValorantMoments:
    env:
      APP_URL: ${{ secrets.APP_URL }}
      CRON_KEY: ${{ secrets.CRON_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        if: ${{ env.APP_URL && env.CRON_KEY }}
        run: |
          curl --request POST \
          --url ${{ secrets.APP_URL }}/api/cron/dailyValorantMoments \
          --header 'Authorization: ${{ secrets.CRON_KEY }}' \
          --fail
